id: ICCE6909C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:07:43+00:00'
last_modified: '2022-06-07T10:24:23.071268+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22265
  title: དབུ་མ་འཇུག་པའི་སྤྱི་དོན་ལེགས་བཤད་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    421A:
      image_group_id: I1KG22283
      title: Volume 1 of dbu ma 'jug pa'i spyi don legs bshad skal bzang mgul rgyan/
      total_pages: 326
      order: 1
      base_file: 421A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
